# Generated by Django 4.2.3 on 2023-11-17 12:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchresource',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='abstract',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchtopic',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='researchtopicregistration',
            name='author_position',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='publishedbook',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
        migrations.RemoveField(
            model_name='researchresource',
            name='attachments',
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='research_app.researchactivitycategory'),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopic',
            name='research_resources',
            field=models.ManyToManyField(blank=True, null=True, to='research_app.researchresource'),
        ),
        migrations.AlterField(
            model_name='researchtopicregistration',
            name='assigned_role',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopicregistration',
            name='registered_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='researchtopicregistration',
            name='registration_approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='technologytransferproject',
            name='signed_contract_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='technologytransferproject',
            name='transfer_contract_id',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='researchresource',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
